"""MCP (Model Context Protocol) orchestration schemas."""

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from .dashboard import AgentMatchResult
from .task import TaskCreate


# ---------------------------------------------------------------------------
# Format
# ---------------------------------------------------------------------------

class MCPFormatRequest(BaseModel):
    """Request to format/summarize a raw job description via the LLM layer."""

    job_id: UUID = Field(..., description="Job to format")


class MCPFormatResponse(BaseModel):
    """Formatted job output from the MCP format step."""

    formatted_summary: str = Field(
        ..., description="LLM-generated structured summary of the job"
    )
    structured_requirements: List[dict] = Field(
        default_factory=list,
        description="Extracted requirements in a machine-readable form",
    )


# ---------------------------------------------------------------------------
# Decompose
# ---------------------------------------------------------------------------

class MCPDecomposeRequest(BaseModel):
    """Request to decompose a job into granular tasks."""

    job_id: UUID = Field(..., description="Job to decompose into tasks")


class MCPDecomposeResponse(BaseModel):
    """Result of job decomposition: a list of tasks to create."""

    tasks: List[TaskCreate] = Field(
        ..., description="Proposed tasks generated by the LLM decomposition step"
    )


# ---------------------------------------------------------------------------
# Match
# ---------------------------------------------------------------------------

class MCPMatchRequest(BaseModel):
    """Request to find the best agents for a given task."""

    task_id: UUID = Field(..., description="Task to find matching agents for")


class MCPMatchResponse(BaseModel):
    """Ranked list of agents suitable for the requested task."""

    ranked_agents: List[AgentMatchResult] = Field(
        ..., description="Agents ranked by combined match score (descending)"
    )


# ---------------------------------------------------------------------------
# Validate
# ---------------------------------------------------------------------------

class MCPValidateRequest(BaseModel):
    """Request to auto-validate a submission via the LLM layer."""

    submission_id: UUID = Field(..., description="Submission to validate")


class MCPValidateResponse(BaseModel):
    """Result of LLM-powered submission validation."""

    decision: str = Field(
        ...,
        pattern=r"^(approved|rejected|needs_revision)$",
        description="Validation verdict",
    )
    notes: Optional[str] = Field(
        None, description="Detailed reasoning for the decision"
    )
    confidence_score: float = Field(
        ..., ge=0.0, le=1.0, description="Model confidence in the decision"
    )


# ---------------------------------------------------------------------------
# Decision audit trail
# ---------------------------------------------------------------------------

class MCPDecisionResponse(BaseModel):
    """Persisted record of an MCP-driven decision (audit log)."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    entity_type: str = Field(
        ..., description="Type of entity the decision pertains to (job, task, submission)"
    )
    entity_id: UUID = Field(
        ..., description="ID of the entity"
    )
    decision_type: str = Field(
        ..., description="Kind of decision (format, decompose, match, validate)"
    )
    reasoning_summary: Optional[str] = Field(
        None, description="LLM-generated reasoning behind the decision"
    )
    confidence_score: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Model confidence score"
    )
    created_at: datetime
